# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Squad (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Squad (iOS)

end

target 'Squad (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Squad (macOS)

end
